export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';
export const GET_POSTS_RESET = 'GET_POSTS_RESET';

export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';
export const UPDATE_POST_RESET = 'UPDATE_POST_RESET';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
export const DELETE_POST_RESET = 'DELETE_POST_RESET';

export const GET_POST_COMMENTS_REQUEST = 'GET_POST_COMMENTS_REQUEST';
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
export const GET_POST_COMMENTS_FAILURE = 'GET_POST_COMMENTS_FAILURE';

export const CREATE_POST_COMMENT_REQUEST = 'CREATE_POST_COMMENT_REQUEST';
export const CREATE_POST_COMMENT_SUCCESS = 'CREATE_POST_COMMENT_SUCCESS';
export const CREATE_POST_COMMENT_FAILURE = 'CREATE_POST_COMMENT_FAILURE';

export const UPDATE_POST_COMMENT_REQUEST = 'UPDATE_POST_COMMENT_REQUEST';
export const UPDATE_POST_COMMENT_SUCCESS = 'UPDATE_POST_COMMENT_SUCCESS';
export const UPDATE_POST_COMMENT_FAILURE = 'UPDATE_POST_COMMENT_FAILURE';

export const DELETE_POST_COMMENT_REQUEST = 'DELETE_POST_COMMENT_REQUEST';
export const DELETE_POST_COMMENT_SUCCESS = 'DELETE_POST_COMMENT_SUCCESS';
export const DELETE_POST_COMMENT_FAILURE = 'DELETE_POST_COMMENT_FAILURE';

export const GET_POST_COMMENT_REPLIES_REQUEST = 'GET_POST_COMMENT_REPLIES_REQUEST';
export const GET_POST_COMMENT_REPLIES_SUCCESS = 'GET_POST_COMMENT_REPLIES_SUCCESS';
export const GET_POST_COMMENT_REPLIES_FAILURE = 'GET_POST_COMMENT_REPLIES_FAILURE';

export const CREATE_POST_COMMENT_REPLY_REQUEST = 'CREATE_POST_COMMENT_REPLY_REQUEST';
export const CREATE_POST_COMMENT_REPLY_SUCCESS = 'CREATE_POST_COMMENT_REPLY_SUCCESS';
export const CREATE_POST_COMMENT_REPLY_FAILURE = 'CREATE_POST_COMMENT_REPLY_FAILURE';

export const UPDATE_POST_COMMENT_REPLY_REQUEST = 'UPDATE_POST_COMMENT_REPLY_REQUEST';
export const UPDATE_POST_COMMENT_REPLY_SUCCESS = 'UPDATE_POST_COMMENT_REPLY_SUCCESS';
export const UPDATE_POST_COMMENT_REPLY_FAILURE = 'UPDATE_POST_COMMENT_REPLY_FAILURE';

export const DELETE_POST_COMMENT_REPLY_REQUEST = 'DELETE_POST_COMMENT_REPLY_REQUEST';
export const DELETE_POST_COMMENT_REPLY_SUCCESS = 'DELETE_POST_COMMENT_REPLY_SUCCESS';
export const DELETE_POST_COMMENT_REPLY_FAILURE = 'DELETE_POST_COMMENT_REPLY_FAILURE';

export const GET_POST_LIKE_REQUEST = 'GET_POST_LIKE_REQUEST';
export const GET_POST_LIKE_SUCCESS = 'GET_POST_LIKE_SUCCESS';
export const GET_POST_LIKE_FAILURE = 'GET_POST_LIKE_FAILURE';

export const CREATE_POST_LIKE_REQUEST = 'CREATE_POST_LIKE_REQUEST';
export const CREATE_POST_LIKE_SUCCESS = 'CREATE_POST_LIKE_SUCCESS';
export const CREATE_POST_LIKE_FAILURE = 'CREATE_POST_LIKE_FAILURE';

export const GET_POST_DISLIKE_REQUEST = 'GET_POST_DISLIKE_REQUEST';
export const GET_POST_DISLIKE_SUCCESS = 'GET_POST_DISLIKE_SUCCESS';
export const GET_POST_DISLIKE_FAILURE = 'GET_POST_DISLIKE_FAILURE';

export const CREATE_POST_DISLIKE_REQUEST = 'CREATE_POST_DISLIKE_REQUEST';
export const CREATE_POST_DISLIKE_SUCCESS = 'CREATE_POST_DISLIKE_SUCCESS';
export const CREATE_POST_DISLIKE_FAILURE = 'CREATE_POST_DISLIKE_FAILURE';



export const GET_POSTS_BY_USER_REQUEST = 'GET_POSTS_BY_USER_REQUEST';
export const GET_POSTS_BY_USER_SUCCESS = 'GET_POSTS_BY_USER_SUCCESS';
export const GET_POSTS_BY_USER_FAILURE = 'GET_POSTS_BY_USER_FAILURE';
export const GET_POSTS_BY_USER_RESET = 'GET_POSTS_BY_USER_RESET';